Hw05 avatars
IraMira333/nodejs-homework-REST-API pull request #5
Opened 2023-09-26 20:48 UTC by IraMira333

2023-09-27 11:12 UTC, ceREAL133 requested changes

2023-09-27 11:12 UTC, ceREAL133 commented on middleware/upload.js
> +    // const filename = `${uniqueSuffix}_${file.originalname}`;
видаліть коменти

2023-09-27 20:27 UTC, IraMira333 commented
Видалила.  Дякую.

2023-09-28 07:50 UTC, ceREAL133 approved these changes

2023-09-28 20:39 UTC, merged